== Implementation
Most of the plugin code is marked as @CompileStatic.

== Auditing and Transactions
All audit events for the entire transaction are queued up.
They are flushed after the transaction has successfully been committed.
This allows the AuditLogListener to use its own session and transaction.

=== AuditLogEventListener
The Audit Logging plugin registers a PersistenceEventListener (`AuditLogListener`) bean per datasource, which listens to GORM events.

=== StampEventListener
The plugin registers a separate StampEventListener that responds to validate events. Ideally, we would stamp when an insert or update event occurs, but since the attributes are non-null by default, we need to populate them before the default validation is triggered.

=== Plugin Descriptor
The Plugin Descriptor (AuditLogListenerGrailsPlugin) configures the plugin during startup.

 * Configures the plugin either by default values - see DefaultAuditLogConfig.groovy - or by user configured settings.
 * Registers a PersistenceEventListener bean per datasource

=== Auditable trait
Enabling auditing on a Domain class is done by implementing the `Auditable` trait.

=== Stampable trait
Enabling stamping on a Domain class is done by implementing the `Stampable` trait.
This trait adds the properties dateCreated, lastUpdated, createdBy and lastUpdatedBy
to the domain class.