== Installation
=== Dependencies
Add to your build.gradle project dependencies block:

[source,groovy]
----
dependencies {
   compile 'org.grails.plugins:audit-logging:{VERSION}'
}
----
Then run the following to refresh gradle dependencies: 

[source,gradle]
----
gradle classes
----

NOTE: After installing the plugin, you must perform the following command to let the plugin create the audit-logging domain class within your project.

=== Create Audit Domain Artifact

    grails audit-quickstart <your.package.name> <YourAuditLogEventClassName>

For example:

    grails audit-quickstart org.myaudit.example AuditTrail

This will create the Audit Domain class and adds to application.groovy:

    grails.plugin.auditLog.auditDomainClassName = 'org.myaudit.example.AuditTrail'
    
Once created, you should open the generated file to adjust the `mappings` and `constraints` to suit your needs.

WARNING: Be sure to respect the existing nullability constraints or the plugin may not work correctly. You must update your db schema either by DDL, or using the database-migration plugin (recommended)

NOTE: Since version 4.0.2 the dateCreated / lastUpdated fields can be of any type which is supported by the Grails DefaultTimestampProvider. By default, they are defined as java.util.Date in the created audit domain artifact. Both fields must be of same type.

=== Prepare your Domain classes for Auditing

For every Domain class you want to be audited, implement the Auditable Trait.

For example:

```groovy
import grails.plugins.orm.auditable.Auditable

class MyDomain implements Auditable {
    String whatever
    ...
}
```


If you additionally want to enable stamping, implement the Stampable Trait:

```groovy
import grails.plugins.orm.auditable.Auditable

 class MyDomain implements Auditable, Stampable {
     String whatever
     ...
 }
```