== Installation
=== Dependencies
Add to your build.gradle project dependencies block:

[source,groovy]
----
dependencies {
   compile 'org.grails.plugins:audit-logging:{version}'
}
----
Then run the following to refresh gradle dependencies: 

[source,gradle]
----
gradle classes
----

NOTE: After installing the plugin, you must perform the following command to let the plugin create the audit-logging domain class within your project.

=== Create Audit Domain Artifact

    grails audit-quickstart <your.package.name> <YourAuditLogEventClassName>

For example:

    grails audit-quickstart org.myaudit.example AuditTrail

This will create the Audit Domain class as well as configure:

    grails.plugin.auditLog.auditDomainClassName = 'org.myaudit.example.AuditTrail'
    
Once created, you should open the generated file to adjust the `mappings` and `constraints` to suit your needs.

WARNING: Be sure to respect the existing nullability constraints or the plugin may not work correctly

=== Prepare your Domain classes for Auditing

For every Domain class you want to be audited, implement the Auditable Trait.

For example:

```groovy
import grails.plugins.orm.auditable.Auditable

class MyDomain implements Auditable {
    String whatever
    ...
}
```


If you additionally want to enable stamping, implement the Stampable Trait:

```groovy
import grails.plugins.orm.auditable.Auditable

 class MyDomain implements Auditable, Stampable {
     String whatever
     ...
 }
```