== Description

The Audit Logging plugin makes it easy to add customizable audit tracking by simply having your domain classes extend the `Auditable` trait.

It also provides a convenient way to add Update and Create user stamping by extending the `Stampable` trait.

=== Compatibility

[cols="1,2",width="50%",options="header,footer"]
|====================
|Grails Version  | Audit Logging Plugin Version
|4.0.0 and later | 5.0.0 (participating in Transactions). This is the recommended version if you use Grails 4.
|4.0.x | 4.0.x
|3.3.x | 3.0.x
|3.0.0 to 3.2.0 | 2.0.x
|2.0.0 to 2.5 | 1.0.x
|1.3.x | 0.5.5.3
|< 1.2.0 | 0.5.3
|====================

=== GORM Compatibility

This plugin is GORM agnostic, so you can use it with the GORM implementation of your choice
(Hibernate 4 or 5, MongoDB, etc.).

Please note, that only Hibernate5 is tested during development. If an issue occurs with your ORM mapper,
please file a GitHub issue.

While the plugin can log transactions for a MongoDB DataSource, it currently does not support MongoDB as an audit logging backend.
If you use this plugin to log MongoDB transactions, you must configure a SQL DataSource for Audit Logging. See Ticket #181.
